### ISSUE TITLE
yarn test で timeout する

### ISSUE THREAD

**Issue by kasaharu** [kasaharu/Pandora#14]
下記のエラーが出る
```
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:4281:23
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/Users/watarukasahara/work/Pandora/node_modules/zone.js/dist/zone.js:421:1)
    at ProxyZoneSpec.webpackJsonp.../../../../zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvokeTask (http://localhost:9876/_karma_webpack_/webpack:/Users/watarukasahara/work/Pandora/node_modules/zone.js/dist/zone-testing.js:263:1)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/Users/watarukasahara/work/Pandora/node_modules/zone.js/dist/zone.js:420:1)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (http://localhost:9876/_karma_webpack_/webpack:/Users/watarukasahara/work/Pandora/node_modules/zone.js/dist/zone.js:188:1)
    at webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/Users/watarukasahara/work/Pandora/node_modules/zone.js/dist/zone.js:496:1)
    at ZoneTask.invoke (http://localhost:9876/_karma_webpack_/webpack:/Users/watarukasahara/work/Pandora/node_modules/zone.js/dist/zone.js:485:1)
    at timer (http://localhost:9876/_karma_webpack_/webpack:/Users/watarukasahara/work/Pandora/node_modules/zone.js/dist/zone.js:2025:1)
```

**Comment by kasaharu** [comment]
- TimerComponent の `ngOnInit()` で Observable を返すメソッドを `subscribe()` している
- TimerComponent は AppComponent から呼ばれる
- app.component.spec.ts 内で AppComponent を `TestBed.createComponent()` した fixture を `detectChanges()` したら、テストが timeout する

**Comment by kasaharu** [comment]
#15 で対応したのでクローズ
